spring.application.name=backend
server.port=8090
spring.datasource.url=jdbc:mysql://localhost:3306/backend?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
weather.api.key=${weather.api.key}

# twilio.account.sid=<REDACTED>
# twilio.auth.token=<REDACTED>
# twilio.phone.number=+14179483330

# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=akhilanallapati3@gmail.com
# spring.mail.password=<REDACTED>
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

huggingface.token=${huggingface.token}

google.places.key=${google.places.key}
