spring.application.name=backend
server.port=8090
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/backend}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

weather.api.key=${WEATHER_API_KEY:59f598e860733fb19ae67d1813bd2f6d}

twilio.account.sid=${TWILIO_SID}
twilio.auth.token=${TWILIO_TOKEN}
twilio.phone.number=${TWILIO_PHONE}

spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=${SENDGRID_API_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

huggingface.token=${HUGGINGFACE_TOKEN}

google.places.key=${GOOGLE_PLACES_KEY:AIzaSyCi0_OOqaa74dAWZ7W8K481hAuJDS9x9VA}
